InnoVisionX/Scool

src/App.jsx
src/components/Footer.jsx
src/components/index.js

feat: completed footer section

---

pnpm-lock.yaml

resolved the bug related to vercel

fix: resolved the bug related to vercel

---

src/App.jsx
src/Routes.jsx
src/pages/404.jsx
src/pages/index.js

-created  404 page UI and route setup
*Screenshots*

feat: Created a 404 page UI and route setup

---

src/pages/Login.jsx

fix: fixed login routes bug

---

vercel.json

feat: added vercel config

---

src/pages/404.jsx
src/pages/index.js

edit: Solved the UI design of 404-page

---

src/App.jsx
src/Routes.jsx
src/components/Login/index.jsx
src/components/Surveys.jsx
src/constants/menus.js
src/pages/404.jsx
src/pages/Dashboard.jsx
src/pages/Home.jsx
src/pages/Login.jsx
src/pages/SingleSurvey.jsx
src/pages/Surveys.jsx
src/pages/index.js

added layout on pages with Outlet component from react router

feat: added layout on pages with Outlet component from react router

---

src/pages/History.jsx

Added History page setup and ui

feat:History Page Completed

---

src/components/Footer.jsx
src/components/SideNav.jsx
src/components/Skeleton/Avatar.jsx
src/components/Skeleton/Text.jsx
src/components/Skeleton/index.js
src/constants/index.js
src/constants/socialMedias.js

added reusable skeleton screens components

feat: added reusable skeleton screens components

---

src/Routes.jsx
src/components/History.jsx
src/components/index.js
src/pages/History.jsx
src/pages/index.js

- Fixed the history page UI
*Screenshots*

fix:historypage UI

---

src/components/Icons/CopyIcon.jsx
src/components/Icons/index.js
src/components/Surveys.jsx
src/pages/History.jsx

- Indexing on Icons Folder
- Import Structure

chore: fixed import structure and added indexing on icons folder.

---

package.json
pnpm-lock.yaml
src/pages/Home.jsx
src/pages/Surveys.jsx

feat:Landing page UI

---

src/components/SideNav.jsx

fix: styling conditional fixed

---

src/components/Login/index.jsx
src/pages/CreateSurvey.jsx

feat: CreateSurvey UI

---

index.html
package.json
pnpm-lock.yaml
src/components/Modals/AddTeacher.jsx
src/components/NavBar.jsx
src/components/SideNav.jsx
src/hooks/index.js
src/hooks/useBaseUrl.js
src/hooks/useSurveysData.js
src/pages/CreateSurvey.jsx
src/pages/Settings.jsx
src/pages/SingleSurvey.jsx
src/pages/Surveys.jsx
src/styles/globals.css

- Create Survey 
- Expiring Feature
- Surveys Page Features like Copy, Download, Delete

feat: create survey completed

---

package.json
pnpm-lock.yaml
src/pages/Contact.jsx

- After sumbitting contact us form a email will be sent to our gmail automatically
- After form Sumbisssion, form will be reset.

feat: After sumbitting contact us form, a email will be sent to our gmail

---

src/hooks/useSurveysData.js
src/pages/Surveys.jsx

- Multiple Re Renders on Surveys Page Fixed

fix: fixed multiple re-renders on surveys page

---

.env

feat: deleted .env

---

pnpm-lock.yaml

fix: build issue fixed

---

package.json
pnpm-lock.yaml
src/components/Participate/Form/StepFour.jsx
src/pages/Participate.jsx

- Participate Survey on Firebase Completed
-  
- 
- 

feat: survey participate backend

---

package.json
pnpm-lock.yaml
src/components/History/index.jsx
src/pages/History.jsx
src/pages/Home.jsx
src/utils/getTimeAgo.js

- 
-  
- 
- Landing Page and History Ui

Landing Page text edit and History Page UI edit

---

.husky/commit-msg
commitlint.config.cjs
package.json
pnpm-lock.yaml

- Husky PreCommit Rules with Commitlint

feat: husky and commit lint setup

---

src/components/History/index.jsx
src/constants/faqs.js
src/pages/History.jsx
src/pages/Home.jsx
src/utils/getExpiredDaysAgo.js

-Added the Filter button and Faqs
-  
- 
- 

feat:Added the Filter button and Faqs

---

src/pages/Home.jsx

fix: build error fix

---

src/constants/team.js

feat: edit roles

---

src/components/History/index.jsx
src/constants/team.js
src/pages/History.jsx

History page filter buttons

---

.github/pull_request_template.md

- Added effective production-grade PR template
-  PR template
- Old PR template
- Effectiveness Issue in PR template

feat: added effective production-grade PR template
